typography_spectrum: 0.49495118111371994
color:
  brandStrength: 0.012497064424678683
  lightness: 0.45615470921620727
  saturation: 0.3201546741183847
  rhythmicContrast: 0.3335984267760068
  brandColors:
    - '#FFFFFF'
    - '#ACB9C0'
    - '#CCC5D7'
    - '#EAE9EF'
    - '#797B9B'
layout_spectrum: 0.2758424358908087
name: CK Dental Solutions
navigation:
  - name: 'Price Guide '
    id: cbf6c276-7d9b-46bd-b67a-2031fae68294
    type: content
  - name: Team
    id: ba7be432-4896-48d4-8071-1cfa95a9c7aa
    type: content
  - name: Dental Implants in Bristol
    id: 9ffe7bb9-1da7-4d2d-bfce-bffe2fddea48
    type: content
  - name: Dental treatment under Sedation
    id: 17bc26ed-9311-43fe-97a2-afcd9b4c9931
    type: content
title: Providing solutions for dental challenges
description: Understanding and helping is our aim
