layout_spectrum: 0.630026914877817
typography_spectrum: 0.31340754707343876
color:
  brandStrength: 0.7801765201147646
  lightness: 0.4904905839357525
  saturation: 0.5422740736976266
  rhythmicContrast: 0.20616812142543495
  brandColors:
    - '#FFFFFF'
    - '#ACB9C0'
    - '#CCC5D7'
    - '#EAE9EF'
    - '#797B9B'
name: CK Dental Solutions
navigation:
  - name: 'Price Guide '
    id: cbf6c276-7d9b-46bd-b67a-2031fae68294
    type: content
  - name: Team
    id: ba7be432-4896-48d4-8071-1cfa95a9c7aa
    type: content
  - name: Dental Implants in Bristol
    id: 9ffe7bb9-1da7-4d2d-bfce-bffe2fddea48
    type: content
  - name: Dental treatment under Sedation
    id: 17bc26ed-9311-43fe-97a2-afcd9b4c9931
    type: content
  - name: Cosmetic Dentist Bristol
    id: 38d4b05c-3c58-4644-9c30-adde36a511aa
    type: content
  - name: Root Canal Treatment
    id: ff6cf017-6bca-4191-965d-d893af2ca9a4
    type: content
  - name: GA for Dental Procedures
    id: 0165747f-c796-4d4a-beb5-ab2823a93a3c
    type: content
  - name: General Dentistry in Bristol
    id: 3f835dd7-6767-4ba4-864d-9c6eb56e481a
    type: content
title: Providing solutions for dental challenges
description: Understanding and helping is our aim
